name: ovorideuser
description: OvoRide is a complete ride-sharing solution.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'


dependencies: 
  flutter:
    sdk: flutter
  dio: ^5.7.0
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  coupon_uikit: ^0.2.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  file_picker: ^8.1.4
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_animate: ^4.5.1
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^18.0.1
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.15
  flutter_widget_from_html: ^0.15.3
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.6.6
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.0
  line_icons: ^2.0.3
  lottie: ^3.1.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  timelines_plus: ^1.0.3
  url_launcher: ^6.3.1
  zoom_tap_animation: ^1.1.0
  rxdart: ^0.28.0
  pusher_channels_flutter: ^2.4.0
  in_app_review: ^2.0.10
  another_flushbar: ^1.12.30
  logger: ^2.5.0
  open_file_plus: ^3.4.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.0
  just_audio: ^0.9.42
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: any
  http: any
  file_picker: any


flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/social/
    - assets/images/logo/
    - assets/images/onboard/
    - assets/icon/
    - assets/icon/files/
    - assets/img/
    - assets/img/icon/
    - assets/img/map/
    - assets/animation/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
