// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhK8l1MFQDzgXAB0p8YY9XLuUmPl_T8SI',
    appId: '1:752138386776:android:bfb4110f5a32839172792d',
    messagingSenderId: '752138386776',
    projectId: 'custom-dodja-errand',
    storageBucket: 'custom-dodja-errand.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFm-o6kwFZKcGIbu3gvV28mLvKcb34-Y',
    appId: '1:752138386776:ios:4d59c82c44e6e70372792d',
    messagingSenderId: '752138386776',
    projectId: 'custom-dodja-errand',
    storageBucket: 'custom-dodja-errand.firebasestorage.app',
    iosBundleId: 'com.dodjaerrands.dodjaerrands',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYrEAr3HoNnmGQNC7qfjbZgurhGizkbuc',
    appId: '1:752138386776:web:0d5b0194cc29fa9772792d',
    messagingSenderId: '752138386776',
    projectId: 'custom-dodja-errand',
    authDomain: 'custom-dodja-errand.firebaseapp.com',
    storageBucket: 'custom-dodja-errand.firebasestorage.app',
  );

}